### ISSUE TITLE
 deprecated warnings in HA Core 2024.1

### ISSUE THREAD

**Issue by Anto79-ops** [libdyson-wg/ha-dyson#107]
hey!

Running beta 2024.1.b0 and looks like there's quite a few changes that have affected the Dyson integration. All my fans are not working. Here are logs, and there are several, and please let me know if you need more information.

```
Logger: homeassistant.components.fan
Source: helpers/entity_platform.py:507
Integration: Fan (documentation, issues)
First occurred: 3:26:16 PM (5 occurrences)
Last logged: 3:26:17 PM

Error adding entities for domain fan with platform dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 406, in capability_attributes
    FanEntityFeature.SET_SPEED in supported_features
TypeError: argument of type 'int' is not iterable
```

```
Logger: homeassistant.components.fan
Source: helpers/entity_platform.py:368
Integration: Fan (documentation, issues)
First occurred: 3:26:16 PM (5 occurrences)
Last logged: 3:26:17 PM

Error while setting up dyson_local platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 406, in capability_attributes
    FanEntityFeature.SET_SPEED in supported_features
TypeError: argument of type 'int' is not iterable
```

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:507
Integration: Climate (documentation, issues)
First occurred: 3:26:16 PM (3 occurrences)
Last logged: 3:26:17 PM

Error adding entities for domain climate with platform dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 333, in capability_attributes
    if ClimateEntityFeature.TARGET_HUMIDITY in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
```
```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:368
Integration: Climate (documentation, issues)
First occurred: 3:26:16 PM (3 occurrences)
Last logged: 3:26:17 PM

Error while setting up dyson_local platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 662, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 333, in capability_attributes
    if ClimateEntityFeature.TARGET_HUMIDITY in supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable
```

```
Logger: homeassistant.components.fan
Source: helpers/deprecation.py:204
Integration: Fan (documentation, issues)
First occurred: 3:26:08 PM (8 occurrences)
Last logged: 3:26:08 PM

SUPPORT_DIRECTION was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.DIRECTION instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
SUPPORT_OSCILLATE was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.OSCILLATE instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
SUPPORT_PRESET_MODE was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
SUPPORT_SET_SPEED was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
```

```
Logger: homeassistant.components.climate.const
Source: helpers/deprecation.py:204
Integration: Climate (documentation, issues)
First occurred: 3:26:11 PM (9 occurrences)
Last logged: 3:26:11 PM

HVAC_MODE_COOL was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
HVAC_MODE_HEAT was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
HVAC_MODE_OFF was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
SUPPORT_FAN_MODE was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
SUPPORT_TARGET_TEMPERATURE was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
```

```
Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 3:25:56 PM (4 occurrences)
Last logged: 3:26:11 PM

TEMP_CELSIUS was used from nest_protect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/imicknl/ha-nest-protect/issues
TEMP_CELSIUS was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
TIME_HOURS was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.HOURS instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
```

**Comment by dotvezz** [comment]
Ahh thanks for the warning! I guess I now what I'll be doing this weekend :sweat_smile:

**Comment by RedNo7** [comment]
I also get this one about changing:
  `custom_components.dyson_local.fan.DysonPureCoolEntity`
to
   `FanEntityFeature.SET_SPEED|OSCILLATE|DIRECTION|PRESET_MODE: 15`

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1520
First occurred: 10:42:54 (2 occurrences)
Last logged: 10:42:54

Entity None (<class 'custom_components.dyson_local.fan.DysonPureCoolEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <FanEntityFeature.SET_SPEED|OSCILLATE|DIRECTION|PRESET_MODE: 15>, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```

**Comment by AnthonyBe** [comment]
Yep, I'm also getting a nice batch of warnings about future deprecations.
My device is a Dyson Pure Hot+Cool Link HP03

```
2024-01-08 18:31:36.746 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.751 WARNING (MainThread) [homeassistant.const] TIME_HOURS was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTime.HOURS instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.761 WARNING (MainThread) [homeassistant.components.binary_sensor] DEVICE_CLASS_BATTERY_CHARGING was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.BATTERY_CHARGING instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.765 WARNING (MainThread) [homeassistant.components.binary_sensor] DEVICE_CLASS_BATTERY_CHARGING was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.BATTERY_CHARGING instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.880 WARNING (MainThread) [homeassistant.components.fan] SUPPORT_DIRECTION was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.DIRECTION instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.884 WARNING (MainThread) [homeassistant.components.fan] SUPPORT_OSCILLATE was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.OSCILLATE instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.889 WARNING (MainThread) [homeassistant.components.fan] SUPPORT_PRESET_MODE was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.895 WARNING (MainThread) [homeassistant.components.fan] SUPPORT_SET_SPEED was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.900 WARNING (MainThread) [homeassistant.components.fan] SUPPORT_DIRECTION was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.DIRECTION instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.905 WARNING (MainThread) [homeassistant.components.fan] SUPPORT_OSCILLATE was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.OSCILLATE instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.911 WARNING (MainThread) [homeassistant.components.fan] SUPPORT_PRESET_MODE was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.916 WARNING (MainThread) [homeassistant.components.fan] SUPPORT_SET_SPEED was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use FanEntityFeature.SET_SPEED instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.956 WARNING (MainThread) [homeassistant.components.climate.const] CURRENT_HVAC_COOL was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.COOLING instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.961 WARNING (MainThread) [homeassistant.components.climate.const] CURRENT_HVAC_HEAT was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.HEATING instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.967 WARNING (MainThread) [homeassistant.components.climate.const] CURRENT_HVAC_IDLE was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.IDLE instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.972 WARNING (MainThread) [homeassistant.components.climate.const] CURRENT_HVAC_OFF was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACAction.OFF instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.978 WARNING (MainThread) [homeassistant.components.climate.const] HVAC_MODE_COOL was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.982 WARNING (MainThread) [homeassistant.components.climate.const] HVAC_MODE_HEAT was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.986 WARNING (MainThread) [homeassistant.components.climate.const] HVAC_MODE_OFF was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.991 WARNING (MainThread) [homeassistant.components.climate.const] SUPPORT_FAN_MODE was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:36.996 WARNING (MainThread) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
2024-01-08 18:31:37.000 WARNING (MainThread) [homeassistant.const] TEMP_CELSIUS was used from dyson_local, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please create a bug report at https://github.com/libdyson-wg/ha-dyson/issues
```

**Comment by codyc1515** [comment]
Fixed by #111

**Comment by dotvezz** [comment]
Please feel free to update to [v1.3.7](https://github.com/libdyson-wg/ha-dyson/releases/tag/v1.3.7) which should resolve this.

**Comment by Anto79-ops** [comment]
thanks for the update!! 1.3.7 fixed like 95% of the error logs. Now, there are only 2:

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:507
Integration: Climate (documentation, issues)
First occurred: 9:29:13 PM (1 occurrences)
Last logged: 9:29:13 PM

Error adding entities for domain climate with platform dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1001, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 384, in state_attributes
    if hvac_action := self.hvac_action:
                      ^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/climate.py", line 72, in hvac_action
    return HVACAction.COOL
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: COOL

```

```
Logger: homeassistant.components.climate
Source: helpers/entity_platform.py:368
Integration: Climate (documentation, issues)
First occurred: 9:29:13 PM (1 occurrences)
Last logged: 9:29:13 PM

Error while setting up dyson_local platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1001, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 384, in state_attributes
    if hvac_action := self.hvac_action:
                      ^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/climate.py", line 72, in hvac_action
    return HVACAction.COOL
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: COOL
```

**Comment by Anto79-ops** [comment]
also, does not look like the fans care compatible with the thermostat cards anymore. I think the sensor has to be `climate.something` versus `fan.something`

**Comment by Anto79-ops** [comment]
oh wait, the climate entity is missing for the hot+cool fans.

**Comment by codyc1515** [comment]
Still there for me.

**Comment by dotvezz** [comment]
@Anto79-ops Aha, your log errors and the climate entity being missing are both the same thing. I'd done a lazy `sed` find-and-replace since all the other new const enums were simple "replace a prefix with another prefix" operations. Turns out the climate entity states also changed from "COOL" to "COOLING" etc.

Fix incoming.

**Comment by Anto79-ops** [comment]
thank you, again! 1.3.9 has solved all issues :)
