### ISSUE TITLE
Cant connect with Hot and cool fan in both Online and device wifi settings

### ISSUE THREAD

**Issue by zsw12abc** [libdyson-wg/ha-dyson#125]
it was working
but after i reboot my router and update to latest version
it didnt work due to IP changed
then i remove my account in homeassisnt and add it back again
i try both wifi and device wifi with the IP address i get from scanning my IP address
still get the following issue.

**_Failed to connect. The IP Address may be required if your Home Assistant installation is running in a Container or a VM._**

**Comment by MarcusKapun** [comment]
I have the exact same issue for some weeks now…

**Comment by K-Aris** [comment]
I'm having the same error when setting up my Dyson fan.

**Comment by pankajr** [comment]
I see that this issue was closed, but I am still seeing this. Here's what i see in the log:
```2025-06-12 23:15:56.042 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry MyDyson: <My email> (US) for dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 963, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 181, in async_unload_entry
    device: DysonDevice = hass.data[DOMAIN][DATA_DEVICES][entry.entry_id]
...skipping...
2025-06-12 23:15:27.014 ERROR (MainThread) [hole] Can not load data from *hole: 172.16.0.10:80
2025-06-12 23:15:56.042 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry MyDyson: rupani.pankaj@gmail.com (US) for dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 963, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 181, in async_unload_entry
    device: DysonDevice = hass.data[DOMAIN][DATA_DEVICES][entry.entry_id]
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '01JXKK07AK...FHM92M'```

**Comment by pankajr** [comment]
Hey friends - I see that this issue was closed, but I am still seeing this. I dont want to open another issue, yet, but here's what I see in the debug logs:
```025-06-12 23:43:16.092 DEBUG (zeroconf-ServiceBrowser-_dyson_mqtt._tcp-_360eye_mqtt._tcp-155) [custom_components.dyson_local.config_flow] Found device at 172.16.0.192
2025-06-12 23:43:16.112 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:16.113 INFO (MainThread) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected to device 9RJ-US-UAC0184A
2025-06-12 23:43:16.176 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:17.242 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:17.252 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:18.268 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:18.277 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:19.293 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:19.300 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:20.317 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:20.337 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:21.350 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:21.360 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:22.389 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:22.428 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:23.446 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:23.457 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:24.476 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:24.492 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:25.508 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:25.519 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:26.554 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:26.608 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:27.631 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:27.650 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:28.680 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:28.689 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:29.703 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:29.719 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:30.748 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:30.787 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:31.800 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:31.811 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:32.829 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:32.859 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:33.898 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:33.919 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:34.963 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:34.990 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:36.004 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 0
2025-06-12 23:43:36.012 DEBUG (paho-mqtt-client-4CE9TtIlZCO6T8W18lqnlT) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 7
2025-06-12 23:43:37.013 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device: DysonConnectTimeout,```

**Comment by pankajr** [comment]
Nevermind this... I see issue#248 is open. I'll follow there.
