### ISSUE TITLE
Error Unloading

### ISSUE THREAD

**Issue by Safi105** [libdyson-wg/ha-dyson#130]
Hello,

I have been getting this error for my TP02 for a few weeks now

Logger: homeassistant.config_entries
Source: config_entries.py:603
First occurred: 09:52:31 (1 occurrences)
Last logged: 09:52:31

Error unloading entry Küche for dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 603, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 187, in async_unload_entry
    device = hass.data[DOMAIN][DATA_DEVICES][entry.entry_id]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '692f0cf9e8a2f2fc33018d64a4b3af35'

**Comment by Ay1tsMe** [comment]
Same issue. I have a dyson purifier cool that suddenly became unavailable. When i try to reload the integration to see if it reconnects it gives me this error.

```
File "/config/custom_components/dyson_local/__init__.py", line 187, in async_unload_entry
    device = hass.data[DOMAIN][DATA_DEVICES][entry.entry_id]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '0394615ca923bfb66bc6d33e62799330'
```

**Comment by Ulrar** [comment]
Same issue here for the past couple of days
