### ISSUE TITLE
Errors in sensor values continue to occur with continuous monitoring off.

### ISSUE THREAD

**Issue by limitless00net** [libdyson-wg/ha-dyson#16]
Errors in sensor values continue to occur with continuous monitoring off. Please indicate the last value or 0 value, not the off value.

Logger: homeassistant
Source: components/sensor/__init__.py:583
First occurred: 09:44:55 (41 occurrences)
Last logged: 09:52:55

Error doing job: Exception in callback Entity.async_write_ha_state()
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'off'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.seonpunggi_temperature has device class temperature, state class measurement unit °C and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: off (<class 'str'>)

**Comment by dotvezz** [comment]
Thanks for the report! This ties right into some work I'm already doing for #4 and can be worked on together.

**Comment by dotvezz** [comment]
[v0.19.0](https://github.com/libdyson-wg/ha-dyson/releases/tag/v0.19.0) has been released. It includes one small change to libdyson which will hopefully address your issue. 

Unfortunately, I wasn't able to replicate the exact behavior from your logs. Disabling continuous monitoring on my 527K didn't have the same result. So if you continue to see this issue after updating, could you also let me know what model you're using?

**Comment by limitless00net** [comment]
@dotvezz After 0.19.0 update, this issue is the same. The model number is Dyson Pure Cool TP04. The device number(?) is 438 on HA device information. The error doesn't occur only when I disable all sensors.

**Comment by mundschenk-at** [comment]
According to a [comment by Baloob](https://github.com/home-assistant/core/issues/92588#issuecomment-1536170238), the problem is that for normally numeric states, `unknown` and `unavailable` should not be used. Instead, the `None` should be assigned as the native value. This is very likely related to https://github.com/home-assistant/core/pull/87013.

**Comment by limitless00net** [comment]
After 0.19.1 update, this issue is the same. Please see the debug logs.

[home-assistant_dyson_local_2023-05-08T01-10-01.504Z.log](https://github.com/libdyson-wg/ha-dyson/files/11416956/home-assistant_dyson_local_2023-05-08T01-10-01.504Z.log)

Logger: homeassistant
Source: components/sensor/__init__.py:583
First occurred: 10:02:33 (187 occurrences)
Last logged: 10:11:33

Error doing job: Task exception was never retrieved
Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'off'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 204, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 349, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 406, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.seonpunggi_humidity has device class humidity, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: off (<class 'str'>)

**Comment by haaino** [comment]
I think the issues are similar, but not the same :-) The first one reported is the "state class measurement unit °C" and this one is "state class measurement unit %". Hope this helps?

**Comment by dotvezz** [comment]
[v0.21.0](https://github.com/libdyson-wg/ha-dyson/releases/tag/v0.21.0) is released which should resolve this issue! Let me know if you have issues @limitless00net!
