### ISSUE TITLE
"Unknown error occurred" when adding account using MyDyson account

### ISSUE THREAD

**Issue by CoffinDocSavage** [libdyson-wg/ha-dyson#184]
After installing the addon using HACS i try to add the device.
I select (NL) and filling in my email address, password and OTP

<img width="371" alt="image" src="https://github.com/user-attachments/assets/613345a4-edbb-4281-9912-b5d2d9078e71">

**Comment by dotvezz** [comment]
Hi there @CoffinDocSavage! Were you able to get this working? If not, feel free to enable debug logging, try again, and share the logs here! That'll be helpful!

**Comment by CoffinDocSavage** [comment]
Hi @dotvezz No, I've just updated the integration but is still shows the same error after trying to put in my password and OTP.
I'm unable to generate the debug logs because I cannot the plugin to work after the password and OTP error

**Comment by dotvezz** [comment]
@CoffinDocSavage are there any error logs related to dyson in your home assistant logs?

**Comment by steveohooto** [comment]
I'm having the same issue.

Updated HA to latest a couple of days ago and then saw there was a Dyson update so installed that too. Rebooted and my fan is no longer connected. Tried removing and readding via account login and got the above error too.

Have then tried rolling back to 1.3.x from 5 months ago and that just flat out won't run at all post reboot - assume because of running too new a version of HA.

Will try again with reinstalling the latest 4.1.x but not hopeful. Pretty broken update so far.

**Comment by dotvezz** [comment]
@steveohooto any chance you're able to enable debug logs and share them here?

**Comment by steveohooto** [comment]
@dotvezz - more than happy to do so, but I'm afraid whilst I'm a geek I'm neither a great HASS geek nor even FOSS geek (Microsoft infrastructure man for 20+ years, sorry!). Can you point me in the right direction to enable the debug logs and where to get them?

FYI nothing related to "dyson" in the main HACore logs that I can see. Also I can't enable debug logs for the integration within Devices & Services as I can't enable the integration without completing setup, which is where it's failing.

I'm using HA Green. Core 2024.8.3, Supervisor 2024.08.0, OS 13.1 and Frontend 20240809.0. Using the Dyson integration v1.4.1.

Thanks.

**Comment by CoffinDocSavage** [comment]
does this help?

`Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:433
First occurred: 18:16:47 (2 occurrences)
Last logged: 18:16:56

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 366, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 413, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 516, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/config_flow.py", line 177, in async_step_email_otp
    auth_info = await self.hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/vendor/libdyson/cloud/account.py", line 181, in _verify
    response = self.request(
               ^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/vendor/libdyson/cloud/account.py", line 117, in request
    raise DysonInvalidAuth
custom_components.dyson_local.vendor.libdyson.exceptions.DysonInvalidAuth`

**Comment by CoffinDocSavage** [comment]
Hi @dotvezz that sehd some light to the case

<img width="531" alt="image" src="https://github.com/user-attachments/assets/e525e410-e373-4b84-ba90-62b934c781d1">

couldn't login to my MyDyson account either, so I've reset my password........

<img width="905" alt="image" src="https://github.com/user-attachments/assets/d4e7b22d-4a34-483a-81e6-2ed758682abc">

And working again.... Thanks!
<img width="251" alt="image" src="https://github.com/user-attachments/assets/48bf01ef-8eee-4802-97ab-5b33e89f0533">

**Comment by steveohooto** [comment]
Thank you - wouldn't have guessed it was due to password changes. Strange how it was working but failed after the update but really pleased it's resolved. Thanks for your efforts @dotvezz .
