### ISSUE TITLE
v1.4.1 - FanEntityFeature breaks install 

### ISSUE THREAD

**Issue by stewart123579** [libdyson-wg/ha-dyson#187]
Just updated --> v1.4.0 --> v1.4.1 today and I get the following error in my logs.

No errors for 1.3.11.

```
Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 12:31:37 PM (2 occurrences)
Last logged: 2:41:35 PM

Error setting up entry Air purifier for dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dyson_local/fan.py", line 59, in <module>
    | FanEntityFeature.TURN_ON
      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'FanEntityFeature' has no attribute 'TURN_ON'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 155, in async_setup_entry
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 151, in setup_entry
    ).result()
      ^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2046, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  [Previous line repeated 2 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1284, in _load_platform
    raise ImportError(
ImportError: Exception importing custom_components.dyson_local.fan
```

**Comment by srgcastor** [comment]
Hi,
I had the same problem since updating to version 1.4.1, and I just removed the integration, restarted HA, and reconfigured everything from scratch, and it worked.

**Comment by dotvezz** [comment]
@stewart123579 you'll just need to update Home Assistant to a more recent version. I'll try to figure out compatibility and post the minimum version supported in 1.4.1

**Comment by stewart123579** [comment]
@dotvezz - Pretty sure that's not it.  I'm running 2024.7.4

I *think* (based on @srgcastor's comment) that there might be some problem when you upgrade 1.3.11 --> 1.4.0 --> 1.4.1 in one go (i.e. no HA restart between).

That is, if I went 1.3.11 --> 1.4.0 then restart.  Then 1.4.0 --> 1.4.1 and a restart might work.

Will try the remove all, restart and the install 1.4.1 and restart approach later.

**Comment by dotvezz** [comment]
@stewart123579 it needs 2024.8 😅

**Comment by stewart123579** [comment]
Re: needing 2024.8 🤣 

Ah, OK.  The docker stable version only moved 2 days ago - I did my update 9 days ago!

Thanks for the clarification.  I'll bump to 2024.8 and then close this ticket.

---

I guess you are already thinking this, but is it possible to put a minimum version requirement in the HACS config?

**Comment by dotvezz** [comment]
@stewart123579 in fact there is a way to do that! I'm going to start using it in a future release, but also looking at ways to satisfy new error logs (conversations about them in #183, #179, #175) without strictly requiring the bleeding edge Home Assistant version.

I'm planning on v1.4.2 to reduce the minimum supported version. I'll add it to hacs.json as well.

**Comment by dotvezz** [comment]
Just a follow-up comment: Since Home Assistant was writing logs telling users to go open an issue here, I assumed that since the deprecation was only 6 months away, the required changes must be compatible with any somewhat-recent version. 

This was a surprise to me as well, but I owe you an apology for not realizing this would happen.

**Comment by stewart123579** [comment]
@dotvezz - LOL - no need to apologise!  

_**Thank you**_ for writing and supporting this integration.

**Comment by dotvezz** [comment]
@stewart123579 I'll go ahead and mark this closed, but feel free to reopen if I'm wrong about 2024.8 resolving your issue.

**Comment by stewart123579** [comment]
Yup, the upgrade solved it.  Thanks @dotvezz
