### ISSUE TITLE
Error in configuration

### ISSUE THREAD

**Issue by aledige63** [libdyson-wg/ha-dyson#191]
Suddenly I've lost the connection th my air purifier. I've therefore tried to reinstall the extension from scratch and I get a message saying that the configuration did no succeed.

Here the log:

Registratore: homeassistant.config_entries
Fonte: config_entries.py:586
Prima occorrenza: 21:01:32 (1 occorrenze)
Ultima registrazione: 21:01:32

Error setting up entry Salotto for dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/dyson_local/fan.py", line 59, in <module>
    | FanEntityFeature.TURN_ON
      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'FanEntityFeature' has no attribute 'TURN_ON'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 155, in async_setup_entry
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 151, in setup_entry
    ).result()
      ^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2046, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  [Previous line repeated 2 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1284, in _load_platform
    raise ImportError(
ImportError: Exception importing custom_components.dyson_local.fan

**Comment by dotvezz** [comment]
Hi @aledige63! Can you share the following?

- Model of your Dyson Device
- Version of your Home Assistant installation
- Version of your HACS installation (if you're using HACS)
- Version of this integration you installed

**Comment by aledige63** [comment]
Many thanks for your reply.

- Dyson PureCool Cryptomic
- HA 2024.7.4
- Hacs 2.0.1
- 1.4.1
I'd like to stress that the integration has been running flawlessly in the past months. I cannot say when exactly the error did appear but surely after a recent update.
Many thanks for your time.

**Comment by dotvezz** [comment]
@aledige63 interesting. One thing I'd like to recommend is either updating your Home Assistant install, or downgrading the Dyson integration to version 1.4.0. 

The minimum supported version of Home Assistant for 1.4.1 is 2024.8.0, due to an unexpected side effect from a change that was prompted by a depreciation warning that started showing up last month. 

In fairness to the Home Assistant people, I should have tested for backwards compatibility and acted appropriately. It's one more thing I'll be adding to my update process moving forward though.

**Comment by dotvezz** [comment]
Ahh yeah, I didn't notice this in your log message previously. That's the compatibility error for v1.4.1 on older versions of Home Assistant.

```AttributeError: type object 'FanEntityFeature' has no attribute 'TURN_ON'```

Out of curiosity, does HACS offer you v1.4.1 without warning about compatibility? The minimum Home Assistant version is declared in hacs.json, so I'd hoped it would prevent installation on incompatible versions...

**Comment by aledige63** [comment]
I've updated to the latest version and is working. I did not upgrade to pastv erions because there were issues with Alexa Media Player. It seems everything has been solved now.
What concerns HACS had no warning at all.
Thank you very much for your support, sorry having bothered you with (at the end of the day) stupid question.

**Comment by dotvezz** [comment]
> What concerns HACS had no warning at all.

Yeah, I'm surprised at this too. I'll keep my eye out for this in the future too.

> sorry having bothered you with (at the end of the day) stupid question.

No trouble at all! Always happy to help.
