### ISSUE TITLE
 My Dyson No longer Showing up in HA ?

### ISSUE THREAD

**Issue by kilrgt** [libdyson-wg/ha-dyson#200]
OK so  this integration , this has worked flawlessly for months, So not sure what happened but my device ( Big and Quiet ) I have done the following: 

removed the device
Deleted the associated account
Yes I restarted HA
Re-added the device
and re -authenticated the account

Device is showing and all of its entities , however none are available  

here is the log, hope it means something to you all ???  Not sure if its isolated to me ???

Logger: homeassistant.config_entries
Source: config_entries.py:809
First occurred: 9:02:28 AM (2 occurrences)
Last logged: 9:02:36 AM

Error unloading entry MyDyson: P-------@ ------.com (CA) for dyson_local
Error unloading entry Living room for dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 809, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 181, in async_unload_entry
    device: DysonDevice = hass.data[DOMAIN][DATA_DEVICES][entry.entry_id]
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '01J6X2SAT65CMGD3V7DK7YN2RQ'



![image](https://github.com/user-attachments/assets/b97ddfb3-c23a-4522-9350-a3abc9dd49c0)

**Comment by kilrgt** [comment]
@dotvezz  Any idea on this issue or suggestions ?

**Comment by kilrgt** [comment]
Magically started working, IM sure it was isolated to my instance .... Ill leave this up for now
