### ISSUE TITLE
Integration fails to load 

### ISSUE THREAD

**Issue by 1192410** [libdyson-wg/ha-dyson#205]
Hello, 

I just have updated Supervisor to the most recent version 2024.11.3. Im running Dyson 1.4.2 and the integration doesn't load anymore. 

Core
2024.11.1
Supervisor
2024.11.3
Operating System
13.2
Frontend
20241106.2

The error logs show this entry: 

2024-11-11 15:50:29.775 DEBUG (Thread-144 (_thread_main)) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 0

Any help would be much appreciated. 

Thanks, 

Andreas

**Comment by meshaabi** [comment]
Also seeing an error since upgrading to 2024.11, wondering if its related ->

heres a dump from the log

`Error unloading entry MyDyson: mesh44380@gmail.com (GB) for dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 850, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 181, in async_unload_entry
    device: DysonDevice = hass.data[DOMAIN][DATA_DEVICES][entry.entry_id]
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'xxxxxxx...'`

**Comment by 1192410** [comment]
Not sure if it was an issue on the Dyson site. Back up and running again without any updates on my side. Closing the issue.
