### ISSUE TITLE
Dyson failed to unload

### ISSUE THREAD

**Issue by RadDip** [libdyson-wg/ha-dyson#209]
After upgrading to HA Core 2024.12.1, receiving Dyson Integration Error "failed to unload.    

Using Dyson integration version 1.4.2.   Rebooted HA several times and tried to reload integration to no avail.

**Comment by freeman59** [comment]
Hello

Same problem here. Updated to last Core and HA version, Dyson is not working anymore, showing "No devices or entities" under MyDyson section.

**Comment by dimitrijez** [comment]
Dyson stopped working for me too.

**Comment by missSp84** [comment]
Hi,

Same problem as stated above. Since I have updated, the Dyson integration does not work anymore. "No devices"  nor entities visible.

**Comment by dotvezz** [comment]
Hmm, I'm on 2024.12.1 and not having any issues. For anyone who is seeing this, are you able to share debug logs to help identify where/why it's happening?

**Comment by RadDip** [comment]
Please see below

2024-12-17 21:38:15.315 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Pure Hot+Cool Link for dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 855, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 181, in async_unload_entry
    device: DysonDevice = hass.data[DOMAIN][DATA_DEVICES][entry.entry_id]
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '01JEGHKQWSKYGX7ZJXHDQEZSPC'

**Comment by CharlPels** [comment]
Same issue and same error by i have 2 dyson pure cools.
One works fine the other is not anymore

**Comment by MLGxPingu** [comment]
I am also having this issue, no devices/entities found

Logger: homeassistant.config_entries
Source: config_entries.py:855
First occurred: 20:21:04 (1 occurrences)
Last logged: 20:21:04

Error unloading entry MyDyson: [my email and region] for dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 855, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 181, in async_unload_entry
    device: DysonDevice = hass.data[DOMAIN][DATA_DEVICES][entry.entry_id]
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '01JFN8B6727G8YEG5JW30P7PJ4'

**Comment by CharlPels** [comment]
> Same issue and same error by i have 2 dyson pure cools. One works fine the other is not anymore
Simple restart etc did not worked
what did worked for me was a redownload of the latest dyson version and reboot again, that solved it for now.
No changes made other then that.

**Comment by MLGxPingu** [comment]
> > Same issue and same error by i have 2 dyson pure cools. One works fine the other is not anymore
> > Simple restart etc did not worked
> > what did worked for me was a redownload of the latest dyson version and reboot again, that solved it for now.
> > No changes made other then that.

Sadly this did not work for me

**Comment by ytchenak** [comment]
Reinstall the Dyson integration and reboot still does not work:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 855, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 181, in async_unload_entry
    device: DysonDevice = hass.data[DOMAIN][DATA_DEVICES][entry.entry_id]
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '01JG0P9N8XRYQM1WDBRSENM6XB'

**Comment by cinghialino** [comment]
Same problem here.

**Comment by ba-johnson** [comment]
Same again here: 

```
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 855, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 181, in async_unload_entry
   device: DysonDevice = hass.data[DOMAIN][DATA_DEVICES][entry.entry_id]
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '...........'
```

I wonder if this is something which has changed in HASS to have caused this maybe for people with older installations. I've had trouble with this plugin for some time which is a shame as it's a great effort.

**Comment by dimitrijez** [comment]
Is there any solution to this? There's still problem with 'failed to unload'...

**Comment by iAmRenzo** [comment]
Nothing?
<img width="295" alt="Image" src="https://github.com/user-attachments/assets/d764362f-d604-41f9-8691-9a20cbaf792a" />

Is this still under development?
