### ISSUE TITLE
Error Connecting to Device

### ISSUE THREAD

**Issue by ahrebel** [libdyson-wg/ha-dyson#210]
I have a HP07, and it worked flawlessly for months, but this morning it said "No Response" on Homekit. I didn't change any settings or anything, and I've tried restoring a Home Assistant backup, deleting the integration and re-adding it, resetting the Dyson device, power cycling the dyson device, turning off and back on the router, adding it from other devices...practically everything I can think of. 

Now, when I try to read it via the integration, it works but says "No Entities or Devices" when I use the MyDyson login option, and says "Failed to connect. The IP Address may be required if your Home Assistant installation is running in a Container or a VM." when I try to do it manually. I've tried using the credential generator linked here as well as for a HomeBridge plugin, and it says it regardless. I've gotten it to appear in Homekit with a Homebridge plugin, so I don't think its the Dyson device. I prefer the HA integration to the Homebridge plugin, so I'm hopeful that this can be resolved. 

I've attached a screenshot of the error message I receive when I do it manually, and of what HA says on the dashboard when I do it using MyDyson login. 

<img width="581" alt="Screenshot 2024-12-08 at 4 40 24 PM" src="https://github.com/user-attachments/assets/41b68a0d-079e-46d1-b321-377dc9b6120a">

<img width="667" alt="Screenshot 2024-12-08 at 4 42 07 PM" src="https://github.com/user-attachments/assets/73f2a394-b9cb-4c70-a00a-90d65aaf2438">

**Comment by dotvezz** [comment]
Hey @ahrebel - can you enable debug logging and share the logs here? Feel free to let me know if you have any questions! Happy to help figure it out, and with logs it will hopefully be pretty easy!

Also, have you had a chance to check the troubleshooting section of the readme? The HP07 is one of a few specific devices that has some known connection quirks, which are covered there.

**Comment by ahrebel** [comment]
Thank you!
I am attaching the logs for when I use the manually setup. I can also do it for the automatic setup with MyDyson login, if needed. I did try power cycling it, which is the only thing I saw in the readme. I did see that HP07 is one of the ones that had some issues, so I made sure to try it. I left it unplugged for quite some time. 

`2024-12-08 16:33:32.327 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-08 16:33:32.328 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-08 16:33:32.329 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration google_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-08 16:33:32.330 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-08 16:33:32.330 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dyson_local which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-08 16:33:32.331 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration worlds_air_quality_index which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-08 16:33:34.299 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'adaptive_lighting' calls async_forward_entry_setup for integration, adaptive_lighting with title: default and entry_id: 01JAEW5V7JMJHS79XEGRC06QVM, which is deprecated, await async_forward_entry_setups instead at custom_components/adaptive_lighting/__init__.py, line 69: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please create a bug report at https://github.com/basnijholt/adaptive-lighting/issues
2024-12-08 16:33:35.729 WARNING (MainThread) [homeassistant.helpers.service] Referenced entities update.dyson_update are missing or not currently available
2024-12-08 16:33:36.341 ERROR (MainThread) [homeassistant.components.camera] The generic platform for the camera integration does not support platform setup. Please remove it from your config.
2024-12-08 16:33:39.133 ERROR (MainThread) [homeassistant.components.homekit] HomeKit Living Room LG TV cannot startup: entity not available: {'exclude_domains': [], 'exclude_entities': [], 'include_domains': [], 'include_entities': ['media_player.living_room_lg_tv_2'], 'exclude_entity_globs': [], 'include_entity_globs': []}
2024-12-08 18:08:05.934 ERROR (Thread-5) [pychromecast.socket_client] [Living Room LG TV(192.168.1.25):8009] Failed to connect to service MDNSServiceInfo(name='65UT8000AUA.BUSCLJM-264b29886c8224448df547eb6b6ce305._googlecast._tcp.local.'), retrying in 5.0s
2024-12-08 18:27:59.825 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry MyDyson: anthonyhrebello@gmail.com (US) for dyson_local
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 855, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/__init__.py", line 181, in async_unload_entry
    device = hass.data[DOMAIN][DATA_DEVICES][entry.entry_id]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '01JEM33RQV3G4MGNMFKSA0713R'
2024-12-08 18:30:30.582 DEBUG (Thread-36 (_thread_main)) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 5
2024-12-08 18:30:30.584 DEBUG (Thread-36 (_thread_main)) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 5
2024-12-08 18:30:31.585 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device: DysonConnectionRefused, 
2024-12-08 18:30:34.447 DEBUG (Thread-37 (_thread_main)) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 5
2024-12-08 18:30:34.448 DEBUG (Thread-37 (_thread_main)) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 5
2024-12-08 18:30:35.450 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device: DysonConnectionRefused, 
2024-12-08 18:30:40.468 DEBUG (Thread-38 (_thread_main)) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 5
2024-12-08 18:30:40.469 DEBUG (Thread-38 (_thread_main)) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 5
2024-12-08 18:30:41.470 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device: DysonConnectionRefused, 
2024-12-08 18:30:42.075 DEBUG (Thread-39 (_thread_main)) [custom_components.dyson_local.vendor.libdyson.dyson_device] Connected with result code 5
2024-12-08 18:30:42.075 DEBUG (Thread-39 (_thread_main)) [custom_components.dyson_local.vendor.libdyson.dyson_device] Disconnected with result code 5
2024-12-08 18:30:43.076 DEBUG (MainThread) [custom_components.dyson_local.config_flow] Failed to connect to device: DysonConnectionRefused, `

**Comment by ahrebel** [comment]
Also, just to make sure I was clear, the two screenshots are not from the same thing. The first one is what happens when I use the manual option (the IP error), and the second is what happens when I do the MyDyson login option (no devices). 

I did see somewhere online that said it took a couple hours for it to work after removing the device from your account and re-adding it, but I wanted 3+ hours and still got that error.

**Comment by Grahamvs** [comment]
I'mnot sure if this is related, but I'm having an issue connecting to one of my devices, and somewhere along the line while trying to fix the issue, I saw the same message as OP. I don't know if it's the same issue or not, but in short:

I have 2 dyson air purifiers, and after updating HA, one of them no longer works. I tried deleting my dyson account link in HA, then re adding it. In the end, I deleted the fan and rebooted my HA hardware (I've got HA Blue). It now sees my fan as a new device, but it fails to add it.

**Comment by ahrebel** [comment]
Unfortunately, I just tried that again, and it still did not work. It's now been nearly 12 hours since I reset the device and re-added it to my account, and it still isn't working, so I'm assuming its not an issue of it just taking time to populate in the account.

**Comment by HandyHat** [comment]
Interestingly, I just encountered a similar issue. I've got a Big + Quiet Formaldehyde BP04 that's been working flawlessly up until now. I got home and Home Assistant refused to control it with the following error:

`2024-12-09 18:26:04.801 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547208652848] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 430, in async_handle_turn_on_service
    await self.async_turn_on(percentage, preset_mode, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 439, in async_turn_on
    await self.hass.async_add_executor_job(
    ...<6 lines>...
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/dyson_local/fan.py", line 174, in turn_on
    self._device.turn_on()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/dyson_local/vendor/libdyson/dyson_purifier_big_quiet.py", line 72, in turn_on
    self._set_configuration(fpwr="ON")
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/config/custom_components/dyson_local/vendor/libdyson/dyson_device.py", line 324, in _set_configuration
    raise DysonNotConnected
custom_components.dyson_local.vendor.libdyson.exceptions.DysonNotConnected`

Reloading the integration did nothing but restarting Home Assistant fixed it.

**Comment by HandyHat** [comment]
Thank you!
My firmware version is currently `066PF.00.08.005.0002`

I only got the air purifier a few days ago so I'm not sure if it was recently updated or not.

I'm happy to open a new issue if you'd like to track this separately? I have no reproduction steps unfortunately.

**Comment by dotvezz** [comment]
@ahrebel am I reading your comment correctly? Sounds like it started working after you disconnected from homebridge, then re-added to Home Assistant. That sounds like it's related to the connection pool limit. It's hard to say _exactly_ what the limit is, but in my testing on my HP07, the limit was low enough that I ran into it a lot.

If that's correct, let's close this thread. @HandyHat if you want to, feel free to open a new issue so we don't accidentally lose track of you when/if closing this one!

**Comment by ahrebel** [comment]
Yes, thats the case, but it wasnt connected to Homebridge originally. I only added it to Homebridge after I tried all the other things listed in my original post. Since its fixed, I'm happy to mark it as closed if you'd like. I also suspect it being a connection pool limit, maybe due to it having previously been connected to Homebridge even if it wasn't actively connected? I don't use Homebridge regularly, so there's a chance it didn't fully disconnect when I turned Homebridge off the last time I used it.

**Comment by dotvezz** [comment]
> maybe due to it having previously been connected to Homebridge even if it wasn't actively connected? I don't use Homebridge regularly, so there's a chance it didn't fully disconnect when I turned Homebridge off the last time I used it.

This is very consistent with the behavior I've seen. For the HP07 and HP09 specifically, when you disconnect from the device, it appears to "forget" to clear/free the connection on its internal broker. So we run into connection limits even when not connected.

I'll mark this as closed, but feel free to follow up if you see any more weirdness!
