### ISSUE TITLE
Error doing job: Task exception was never retrieved (41,110 occurrences in 15 hrs)

### ISSUE THREAD

**Issue by RedNo7** [libdyson-wg/ha-dyson#22]
Hi,

I *think* this is `ha-dyson` based on the last line of the log entry
```
ValueError: Sensor sensor.pure_cool_humidity has device class humidity, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: off (<class 'str'>)
```

Any ideas?
Full log below.

By the way, *awesome* job on keeping `ha-dyson` working for us all!

```
Logger: homeassistant
Source: components/sensor/__init__.py:583
First occurred: 11 May 2023 at 17:06:11 (41110 occurrences)
Last logged: 09:25:52

Error doing job: Task exception was never retrieved
Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'off'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 204, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 349, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 406, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.pure_cool_humidity has device class humidity, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: off (<class 'str'>)

```

**Comment by RedNo7** [comment]
edit:  I'm not sure why, but my Dyson had disconnected from the network.

**Comment by dotvezz** [comment]
Glad you got it working!

**Comment by RedNo7** [comment]
Hi!

OK, it's a problem whenever I have "continuous monitoring" switched off (although the problem will also occur if the device is disconnected from the network.

The logs are essentially the same as above, but it appears to be only associated with 'humidity' (not the other other sensors that go 'unavailable' when 'continuous monitoring' is off.  Also, I was sure that these sensors did not go `unavailable` with the 'old' Dyson-local - maybe it just kept the last reading?

Either way, here are the logs again:
```
Logger: homeassistant
Source: components/sensor/__init__.py:583
First occurred: 10:13:44 (49 occurrences)
Last logged: 10:14:44

Error doing job: Task exception was never retrieved
Error doing job: Exception in callback Entity.async_write_ha_state()
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'off'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 204, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 349, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 146, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 406, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.pure_hot_cool_humidity has device class humidity, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: off (<class 'str'>)
```

I guess the key line is the last one:
```
ValueError: Sensor sensor.pure_hot_cool_humidity has device class humidity, state class measurement unit % and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: off (<class 'str'>)
```

**Comment by dotvezz** [comment]
Aha okay, this we can work with. Thanks for all the info.

**Comment by RedNo7** [comment]
cheers.

...any news on this?

**Comment by dotvezz** [comment]
No updates yet, but I haven't forgotten!

**Comment by RedNo7** [comment]
Cheers 👍🏻

**Comment by jamincollins** [comment]
Noting that I'm also affected by this...

```
Jun 25 12:53:41 home-assistant hass[376053]: 2023-06-25 12:53:41.130 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Jun 25 12:53:41 home-assistant hass[376053]: Traceback (most recent call last):
Jun 25 12:53:41 home-assistant hass[376053]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 581, in state
Jun 25 12:53:41 home-assistant hass[376053]:     numerical_value = int(value)
Jun 25 12:53:41 home-assistant hass[376053]:                       ^^^^^^^^^^
Jun 25 12:53:41 home-assistant hass[376053]: ValueError: invalid literal for int() with base 10: 'init'
Jun 25 12:53:41 home-assistant hass[376053]: The above exception was the direct cause of the following exception:
Jun 25 12:53:41 home-assistant hass[376053]: Traceback (most recent call last):
Jun 25 12:53:41 home-assistant hass[376053]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 229, in _handle_refresh_interval
Jun 25 12:53:41 home-assistant hass[376053]:     await self._async_refresh(log_failures=True, scheduled=True)
Jun 25 12:53:41 home-assistant hass[376053]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 374, in _async_refresh
Jun 25 12:53:41 home-assistant hass[376053]:     self.async_update_listeners()
Jun 25 12:53:41 home-assistant hass[376053]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 164, in async_update_listeners
Jun 25 12:53:41 home-assistant hass[376053]:     update_callback()
Jun 25 12:53:41 home-assistant hass[376053]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 431, in _handle_coordinator_update
Jun 25 12:53:41 home-assistant hass[376053]:     self.async_write_ha_state()
Jun 25 12:53:41 home-assistant hass[376053]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 590, in async_write_ha_state
Jun 25 12:53:41 home-assistant hass[376053]:     self._async_write_ha_state()
Jun 25 12:53:41 home-assistant hass[376053]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 654, in _async_write_ha_state
Jun 25 12:53:41 home-assistant hass[376053]:     state = self._stringify_state(available)
Jun 25 12:53:41 home-assistant hass[376053]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 25 12:53:41 home-assistant hass[376053]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 596, in _stringify_state
Jun 25 12:53:41 home-assistant hass[376053]:     if (state := self.state) is None:
Jun 25 12:53:41 home-assistant hass[376053]:                  ^^^^^^^^^^
Jun 25 12:53:41 home-assistant hass[376053]:   File "/var/lib/hass/.venv/lib/python3.11/site-packages/homeassistant/components/sensor/__init__.py", line 585, in state
Jun 25 12:53:41 home-assistant hass[376053]:     raise ValueError(
Jun 25 12:53:41 home-assistant hass[376053]: ValueError: Sensor sensor.pure_cool_link_volatile_organic_compounds_index has device class 'aqi', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'init' (<class 'str'>)
```

**Comment by RedNo7** [comment]
I have had to disable the following sensors on all my Dyson's to stop my logs blowing to such a degree that it was slowing down my HA
- humidity
- nitrogen_dioxdide_index
- pm_10
- pm_2_5
- temperature
- volatile_organic_compounds_index

...basically all the sensors affected when continuous monitoring is off.

**Comment by dotvezz** [comment]
@RedNo7 sorry for the delay! [v0.21.0](https://github.com/libdyson-wg/ha-dyson/releases/tag/v0.21.0) is released which hopefully addresses this.

**Comment by RedNo7** [comment]
looks like that's fixed it - thanks so much!! 👍
