### ISSUE TITLE
Intergration error

### ISSUE THREAD

**Issue by linkwellfook** [libdyson-wg/ha-dyson#26]
Home Assistant 2023.5.3 
Supervisor 2023.04.1 
Operating System 10.1 
Frontend 20230503.3 - latest 

VM hosted on Ubuntu 23.04 
current version of Virtualbox

Removed the previous ha-local and ha-cloud repos and the current ones
Attepted to install intergrations
Received following error message
Config flow could not be loaded: {"message":"Invalid handler specified"}

Enabled logging
Log snippet

ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration dyson_local: Exception importing custom_components.dyson.config_flow

...
ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration dyson_cloud: cannot import name 'DysonPureHumidifyCool' from 'libdyson' (/usr/local/lib/python3.10/site-packages/libdyson/__init__.py)

ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.dyson.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/dyson/__init__.py", line 31
    <title>core/__init__.py at dev · home-assistant/core</title>
                                   ^
SyntaxError: invalid character '·' (U+00B7)
2023-05-23 21:52:02.637 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration dyson_local: Exception importing custom_components.dyson.config_flow

**Comment by dotvezz** [comment]
That error looks like it didn't install the updated libdyson release - did you restart your Home Assistant server to make sure it (re)installs the component dependencies?

**Comment by linkwellfook** [comment]
did you restart your Home Assistant server to make sure it (re)installs the component dependencies:  Yeap
Also logged out of the android app.

Removed local and cloud intergrations (both versions)
Restarted HA
Added intergrations again (both versons)
Rebooted HA
This time I can set up cloud version but not local version

**Comment by dotvezz** [comment]
How odd, sorry that's happening to you. Can you check the version of libdyson-neon that's installed in Home Assistant's venv?

**Comment by linkwellfook** [comment]
I cloned libdyson-neon and ran the requirements file

If I run get_devices.py I get the following trace

Please choose your account region
1: Mainland China
2: Rest of the World
Region [1/2]: 2
Region code: ie
Email: redacted
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/libdyson-neon/get_devices.py", line 22, in <module>
    verify = account.login_email_otp(email, region)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/libdyson-neon/libdyson/cloud/account.py", line 161, in login_email_otp
    jsonRes = response.json()
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Then tried EU

libdyson-neon $ python3 get_devices.py
Please choose your account region
1: Mainland China
2: Rest of the World
Region [1/2]: 2
Region code: eu
Email: redacted
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/libdyson-neon/get_devices.py", line 22, in <module>
    verify = account.login_email_otp(email, region)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/libdyson-neon/libdyson/cloud/account.py", line 161, in login_email_otp
    jsonRes = response.json()
              ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Note I get the same results if I'm logged in on the dyson app or if I log out.
The dyson app is up to date.

**Comment by dotvezz** [comment]
Thanks for following up. The get-devices script is *very* particular about inputs. The errors you're getting there are specifically because you used lowercase region codes - it requires you to input the region code in uppercase. One of the projects I'm working on is a full-fledged CLI to replace the get-devices script, but for now it's what we've inherited from shenxn.

Can you check the version of libdyson-neon that's installed in your home-assistant venv?

**Comment by linkwellfook** [comment]
Hi,
Taken from setup.cfg
version = 1.0.2

Was not the region code should be upper case

It ran successfully.

IThe device type is 527
I have the credentials.

Tried dyson local and the error appeared again

**Comment by dotvezz** [comment]
> Was not the region code should be upper case

Oh cool, what was it?

**Comment by linkwellfook** [comment]
*correction*  Was not aware that the region code should be upper case.  It was IE

**Comment by dotvezz** [comment]
Aha, gotcha. Yeah I ran into that stumbling block myself, I'm aware of how un-ergonomic it's on the list of things I want to make better.

For your original issue, I've taken a closer look at your logs (thanks again for pasting) and am really confused how you're getting that. There are a few things in the log entry you pasted that don't make sense to me:

1. cannot import name 'DysonPureHumidifyCool' from 'libdyson' 
    - This should  **_literally never_** happen because there is nothing called `DysonPureHumidifyCool`  in the current version of this integration, the cloud integration, or the Dyson integration.
2. It references a path `/custom_components/dyson/` which (to my knowledge) should not exist when using HACS to install this integration. The path this integration will normally install to is `custom_components/dyson-local/`
    - Are you installing the integration through some method other than HACS?
3. It references a file `init.py` (`/custom_components/dyson/init.py`) which does not exist in this integration.
    - Is there some customization happening?

So my new questions for you:
1. Which releases of the ha-dyson and ha-dyson-cloud repositories are you using?
2. Which version of the ha-dyson and ha-dyson-cloud are you using? (Are you using a mix of shenxn's and libdyson-wg's?)
3. What installation method are you using?

**Comment by linkwellfook** [comment]
Hi,

    Which releases of the ha-dyson and ha-dyson-cloud repositories are you using?
      libdyson-wg
    Which version of the ha-dyson and ha-dyson-cloud are you using? (Are you using a mix of shenxn's and libdyson-wg's?)
     Dyson-local - v0.19.1
     Dyson-cloud - v0.18.1
    What installation method are you using?
      HACS

I had both repos installed and got the error.  
I removed shenxn's repo  after running the update repos rebooted ha and tried to add the dyson local only for the error to appear.
I removed all repos and only installed libdyson-wg then after another reboot tried to add the local intergration again only for the error to appear yet again.

**Comment by linkwellfook** [comment]
Hi,
I'm no longer getting the error.
I am getting ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration dyson_local: Exception importing custom_components.dyson.config_flow.
This coresponds wit the dialog message 
Config flow could not be loaded: {"message":"Invalid handler specified"}

log levels set to debug
libdyson: debug
custom_components.dyson_local: debug
custom_components.dyson_cloud: debug

**Comment by dotvezz** [comment]
Hi @linkwellfook, sorry for the long delay here. I've published a new release of this integration, as well as the cloud integration, which vendors the libdyson dependency. I'm hoping this solves your problem, but let me know if you have continued issues after updating!

https://github.com/libdyson-wg/ha-dyson/releases/tag/v0.20.0
https://github.com/libdyson-wg/ha-dyson-cloud/releases/tag/v0.19.0

**Comment by dotvezz** [comment]
Okay part of that is my fault - libdyson has some self-referencing imports that are causing the `DysonAPIProvisionFailure` import failure. https://github.com/libdyson-wg/ha-dyson-cloud/releases/tag/v0.19.1 should fix it.

But the other part, where It references `/config/custom_components/dyson/init.py` still, is very weird. This integration is `custom_components/dyson_local`. So I have no idea why you have a `custom_components/dyson` path at all.

**Comment by linkwellfook** [comment]
Hi,
So I did the following
I remain logged out of the Android Dyuson app  

Disabled both intergrations
Removed both interdrations
Remove the HACS install
Deleted all references to dyson from the custom_component directory
rebooted HA

Installed the intergrations from HACS
rebooted HA
Successfully configured Dyson Cloud
Dyson Cloud shows 'no device or entiries'

Tried to configure Dyson Local 
Again, I got
Config flow could not be loaded: {"message":"Invalid handler specified"

The logs

2023-06-08 21:17:18.991 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration dyson_local: cannot import name 'DysonAPIProvisionFailure' from 'libdyson.exceptions' (/usr/local/lib/python3.11/site-packages/libdyson/exceptions.py)

2023-06-08 21:17:18.994 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2029, in _load_integration
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/dyson_local/config_flow.py", line 8, in <module>
    from .vendor.libdyson.cloud import DysonDeviceInfo
  File "/config/custom_components/dyson_local/vendor/libdyson/cloud/__init__.py", line 3, in <module>
    from .account import DysonAccount, DysonAccountCN  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/vendor/libdyson/cloud/account.py", line 9, in <module>
    from libdyson.exceptions import (
ImportError: cannot import name 'DysonAPIProvisionFailure' from 'libdyson.exceptions' (/usr/local/lib/python3.11/site-packages/libdyson/exceptions.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 845, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 863, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 962, in async_create_flow
    await _load_integration(self.hass, handler_key, self._hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2036, in _load_integration
    raise data_entry_flow.UnknownHandler
homeassistant.data_entry_flow.UnknownHandler


dyson_local manifest
{
    "domain": "dyson_local",
    "name": "Dyson Local",
    "config_flow": true,
    "documentation": "https://github.com/libdyson-wg/ha-dyson",
    "issue_tracker": "https://github.com/libdyson-wg/ha-dyson/issues",
    "dependencies": ["zeroconf"],
    "codeowners": ["@libdyson-wg"],
    "requirements": ["libdyson-neon==1.0.2"],
    "version": "0.20.0",
    "iot_class": "local_polling"
}

Dyson cloud manifest

{
    "domain": "dyson_cloud",
    "name": "Dyson Cloud",
    "config_flow": true,
    "documentation": "https://github.com/libdyson-wg/ha-dyson-cloud",
    "issue_tracker": "https://github.com/libdyson-wg/ha-dyson-cloud/issues",
    "dependencies": [],
    "codeowners": ["@libdyson-wg"],
    "requirements": [],
    "version": "0.19.0"
}

The version in hacs show 0.19.1

Best Regards

**Comment by dotvezz** [comment]
Thanks for all your work on those logs, and I wish you'd been having a better experience so far. I wish this was something I was able to reproduce in my testing, that way it wouldn't have impacted you.

I'm happy to see that the mysterious `custom_components/dyson/` path isn't in your logs anymore. I still have no idea why it was there, but it's gone now and I was able to make sense of the rest. It looks like the cloud integration 0.19.1 resolved some of your previous logs, but you're seeing the same behavior on the local integration now. So I've cut a new release that has the same fix: https://github.com/libdyson-wg/ha-dyson/releases/tag/v0.20.1

I'll be sure to ramp up my integration testing moving forward so this kind of thing doesn't happen again. I need to be a better steward for the project :sweat_smile:.

**Comment by linkwellfook** [comment]
Hi,

It looks like the last update to dyson local did the trick.

The intergration found the Dyson device and created the following entities

fan.kitchen
sensor.kitchen_humidity
sensor.kitchen_temperature
sensor.kitchen_volatile_organic_compounds_index
sensor.kitchen_pm_2_5
sensor.kitchen_pm_10
sensor.kitchen_nitrogen_dioxide_index
sensor.kitchen_carbon_filter_life
sensor.kitchen_hepa_filter_life
switch.kitchen_night_mode
switch.kitchen_continuous_monitoring
climate.kitchen

Checking the entities in the Developer tab I can see that they are active and displaying their attributes.

Best Regards
