### ISSUE TITLE
Error while setting up dyson_local platform for camera

### ISSUE THREAD

**Issue by codyc1515** [libdyson-wg/ha-dyson#53]
This is on v1.0.0
```
Logger: homeassistant.components.camera
Source: custom_components/dyson_local/camera.py:23
Integration: Camera (documentation, issues)
First occurred: 14:06:36 (1 occurrences)
Last logged: 14:06:36

Error while setting up dyson_local platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/dyson_local/camera.py", line 23, in async_setup_entry
    data = hass.data[DOMAIN][config_entry.entry_id]
           ~~~~~~~~~^^^^^^^^
KeyError: 'dyson_cloud'

```

**Comment by dotvezz** [comment]
Aha, yeah this is my fault. I'll have a fix up soon.

**Comment by dotvezz** [comment]
Okay, [v1.0.1](https://github.com/libdyson-wg/ha-dyson/releases/tag/v1.0.1) fixes this silly mistake.

**Comment by dotvezz** [comment]
@codyc1515, I'll close this issue but if it turns out the new release didn't fix it then please feel free to reopen it.
