### ISSUE TITLE
Error on trying to add discovered Device

### ISSUE THREAD

**Issue by kilrgt** [libdyson-wg/ha-dyson#62]
Hi All,

Little help here. I’m not even sure if the model i have is compatible ,i have the new Big and Quiet Air purifier. I have added the Dyson via Hacs Successfully, added my Dyson account and shows with no entities. HA does Discover my device, I go to try and setup and all i get is “unknown error occurred” in the pop up there is a “ IP address  optional “ I don't add anything there, I cant find the device on my network , yes its odd but the app works with no issue. Can someone please o please steer me in the right direction. 
No logs, so i cant provide much detail, however i will add  happily provide any info I can, running on a pie With OS
![IMG_3358](https://github.com/libdyson-wg/ha-dyson/assets/97072590/ea8e29d2-4df1-47fa-b3a5-c7ea6a123e54)

**Comment by kilrgt** [comment]
https://github.com/dotvezz If anyone can figure this out its you!

**Comment by dotvezz** [comment]
Hi @kilrgt! Thanks for opening this. I have some of work to do on my end to add support for the Big+Quiet. 

Full disclosure, there's a new small human living in my house (which is to say, we had a baby) and I also started a new job recently. I haven't _quite_ had as much time to add new features as I'd like. But we have a long weekend coming up so :crossed_fingers: .

**Comment by kilrgt** [comment]
Congratulations on the baby and new Job! Don’t worry about this stuff, real life is more important! Honestly I appreciate the reply, you have your hands full…this can wait 

Thanks for all the work you do for this community! 

Congrats again, Awesome and exciting times!

**Comment by kilrgt** [comment]
Just wanted to post the log, it may help?

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/dyson_local/vendor/libdyson/discovery.py:30 
Integration: Dyson (documentation, issues) 
First occurred: August 31, 2023 at 7:25:37 PM (7 occurrences) 
Last logged: 5:55:01 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 181, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 296, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 392, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/config_flow.py", line 309, in async_step_host
    data = await self._async_get_entry_data(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dyson_local/config_flow.py", line 358, in _async_get_entry_data
    await self._async_try_connect(serial, credential, device_type, host)
  File "/config/custom_components/dyson_local/config_flow.py", line 388, in _async_try_connect
    discovery.register_device(device, _callback)
  File "/config/custom_components/dyson_local/vendor/libdyson/discovery.py", line 30, in register_device
    if device.serial in self._discovered:
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'serial'

**Comment by dotvezz** [comment]
@kilrgt the log was helpful, thanks! [v1.1.0](https://github.com/libdyson-wg/ha-dyson/releases/tag/v1.1.0) is released with initial support fir Big+Quiet devices. There may be things that are missing, especially if there are new features unique to Big+Quiet which I don't know about yet. Feel free to check it out and let me know!

**Comment by kilrgt** [comment]
@dotvezz 

All is good, integration now works perfect with the Big & Quiet . Thanks for helping me out and taking the time... I'm sure you are rather busy with all going on!
