### ISSUE TITLE
device reset after update

### ISSUE THREAD

**Issue by Silther** [libdyson-wg/ha-dyson#83]
![image](https://github.com/libdyson-wg/ha-dyson/assets/97352673/646ebae7-9a00-408e-ae1b-b04128ad5fe7)

**Comment by niemtec** [comment]
Having the same issue

**Comment by dotvezz** [comment]
I'm really scratching my head over this one. v1.3.2 should be pretty much a non-issue for existing devices. The only changes to device connections in libdyson or the integration are...

- [a simple added prop](https://github.com/libdyson-wg/ha-dyson/compare/v1.2.0...v1.3.2#diff-a6959b86d22c13894f7841ac4dc911a4e594ab2967c49509d646c68ab4c6cbb6R65-R69) for the Carbon Dioxide sensor on Big+Quiet filters.
- [a related class](https://github.com/libdyson-wg/ha-dyson/compare/v1.2.0...v1.3.2#diff-dda56c1efaf4d447e03397f711ff17e74e660c331125ecf77de1bb6f537c3b0dR397-R417) for the same sensor.
- [an initialization check to load the CO2 sensor)[https://github.com/libdyson-wg/ha-dyson/compare/v1.2.0...v1.3.2#diff-dda56c1efaf4d447e03397f711ff17e74e660c331125ecf77de1bb6f537c3b0dR397-R417].
- [a button entity](https://github.com/libdyson-wg/ha-dyson/compare/v1.2.0...v1.3.2#diff-571c020dc48f6139371a37864fd9703cb9e850e363ca97a42522d3542c823e9b) for resetting filters on some devices.
- [a simple check to load the button platform if needed](https://github.com/libdyson-wg/ha-dyson/compare/v1.2.0...v1.3.2#diff-6775c16d9175e14b51de0a91a50aa195fd297e6ffd843f4b99960855dc2d2d78R215-R216)

And that's it. I'll see if I can figure out what's going on though.

@Silther I'm glad you were able to get it to work, but I have to recognize that "delete all devices" step has got to suck. @niemtec is your issue also with a Pure Cool Link device?

**Comment by niemtec** [comment]
Mines a Dyson Purifier Cool Formaldehyde

**Comment by dotvezz** [comment]
@Silther are you able to grab debug logs and post them here? We might be able to dig a bit deeper and identify the problem with that.

**Comment by Arkaivos** [comment]
Same problem here, it stopped working (I had not updated to v1.3.2 yet when it happened).

**Comment by dotvezz** [comment]
Hey @Silther, just wanted to check and see if you're still having this issue.

**Comment by codyc1515** [comment]
How did you get on with this?

**Comment by codyc1515** [comment]
I think I had to do this too. Thanks for sharing and glad to hear it’s working now.

**Comment by onkatr** [comment]
I have the same problem with one of my Purifier Humidify+Cool Formaldehyde. I have got tow of them, the other one is working perfectly. The Auto detect is finding the other one but I cannot add it.  I have tried all the steps, like static IP, reinstall etc. Here is my debug log.

This error originated from a custom integration.

Logger: root
Source: custom_components/dyson_local/vendor/libdyson/discovery.py:80
Integration: Dyson (documentation, issues)
First occurred: 3:47:01 PM (7 occurrences)
Last logged: 4:03:16 PM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/zeroconf/_utils/asyncio.py", line 113, in run_coro_with_timeout
    return asyncio.run_coroutine_threadsafe(aw, loop).result(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 458, in result
    raise TimeoutError()
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "src/zeroconf/_services/browser.py", line 783, in zeroconf._services.browser.ServiceBrowser.run
  File "src/zeroconf/_services/browser.py", line 702, in zeroconf._services.browser._ServiceBrowserBase._fire_service_state_changed_event
  File "src/zeroconf/_services/browser.py", line 712, in zeroconf._services.browser._ServiceBrowserBase._fire_service_state_changed_event
  File "src/zeroconf/_services/__init__.py", line 56, in zeroconf._services.Signal.fire
  File "src/zeroconf/_services/browser.py", line 290, in zeroconf._services.browser._on_change_dispatcher
  File "/config/custom_components/dyson_local/vendor/libdyson/discovery.py", line 80, in add_service
    info = zeroconf.get_service_info(type, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/zeroconf/_core.py", line 266, in get_service_info
    if info.request(self, timeout, question_type):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/zeroconf/_services/info.py", line 778, in zeroconf._services.info.ServiceInfo.request
  File "/usr/local/lib/python3.12/site-packages/zeroconf/_utils/asyncio.py", line 117, in run_coro_with_timeout
    raise EventLoopBlocked from ex
zeroconf._exceptions.EventLoopBlocked
