### ISSUE TITLE
Dyson eye 360 cleaning map not shown / empty

### ISSUE THREAD

**Issue by shavermcspud** [libdyson-wg/ha-dyson#92]
Core
2023.11.2
Supervisor
2023.11.3
Operating System
11.1
Frontend
20231030

Dyson add on latest

![image](https://github.com/libdyson-wg/ha-dyson/assets/96439393/b12e1cdf-1ef3-43f7-b141-f0363ee8ebdf)

**Comment by dotvezz** [comment]
Hmm, interesting. This is an area of the integration that doesn't get a lot of attention these days.. Could you enable debug logging for the integration and share the logs here?

**Comment by iMiMx** [comment]
I saw something similar with the 'other' Dyson integration - it seems someone managed to work it out:

https://github.com/shenxn/ha-dyson-cloud/issues/2

**Comment by dotvezz** [comment]
Interesting! I'll reach out to @condor872 and see if we can integrate his solution here. Thanks @iMiMx!

**Comment by dotvezz** [comment]
Update: @condor872 has replied on https://github.com/shenxn/ha-dyson-cloud/issues/2, we may have a working solution for this soon. :crossed_fingers:.

**Comment by rick2909** [comment]
Can't wait for this to be implemented. does this also include the ability to send the vacuum to only clean the selected zone(s)?

**Comment by FilipPyrek** [comment]
Being able to send the vacuum only to selected zone is quite important. So it would be great to have 😊

**Comment by jonnymullen** [comment]
I got mine working by altering the following in camera.py

```
def camera_image(self):
    """Return cleaning map."""
    return self._image

```
replace with 

```
def camera_image(self, width=None, height=None):
    """Return cleaning map. Width and height are ignored."""
    return self._image
```

**Comment by iMiMx** [comment]
Thanks for the input @jonnymullen - may I ask which model you have?

**Comment by dotvezz** [comment]
@jonnymullen wait was it really that easy??? I might just throw up a release candidate tonight for this for y'all to test.

**Comment by VibroAxe** [comment]
Looks like somewhere the original implementation broke with the camera method signature. Update PR coming in with assistance from @jonnymullen

**Comment by rick2909** [comment]
this did sadly not fix it for me the Dyson 360 Heurist still doesn't show a map in HA.

**Comment by VibroAxe** [comment]
> this did sadly not fix it for me the Dyson 360 Heurist still doesn't show a map in HA.

Interesting. Works for the 360 eye standard. I wonder if they Heurist uses a different end point. What error do you get?

**Comment by VibroAxe** [comment]
> I get the following error in the logs from dyson integration. and 2 warnings but those are for the soon deprecated states enum.
> ```
> Logger: homeassistant
> Source: custom_components/dyson_local/vendor/libdyson/dyson_360_heurist.py:20
> integration: Dyson ([documentation](https://github.com/libdyson-wg/ha-dyson), [issues](https://github.com/libdyson-wg/ha-dyson/issues))
> First occurred: June 12, 2025 at 15:38:08 (8 occurrences)
> Last logged: June 12, 2025 at 22:53:48
> 
> Error doing job: Exception in callback Entity._async_write_ha_state_from_call_soon_threadsafe() (None)
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
>     self._context.run(self._callback, *self._args)
>     ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1010, in _async_write_ha_state_from_call_soon_threadsafe
>     self._async_write_ha_state()
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1141, in _async_write_ha_state
>     self.__async_calculate_state()
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1083, in __async_calculate_state
>     if state_attributes := self.state_attributes:
>                            ^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 340, in state_attributes
>     data[ATTR_FAN_SPEED] = self.fan_speed
>                            ^^^^^^^^^^^^^^
>   File "/config/custom_components/dyson_local/vacuum.py", line 231, in fan_speed
>     return HEURIST_POWER_MODE_ENUM_TO_STR[self._device.current_power_mode]
>                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/dyson_local/vendor/libdyson/dyson_360_heurist.py", line 20, in current_power_mode
>     return VacuumHeuristPowerMode(self._status["currentVacuumPowerMode"])
>                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
> KeyError: 'currentVacuumPowerMode'
> ```

This looks unrelated to the video feed but is doing the Heurist from registering it's entities or something. @dotvezz suggest this is moved to a new issue

**Comment by jubepue** [comment]
No news for the heuristic map?
